version: '3.1'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: pro-ttareungler-postgis
    restart: 'no'
    environment:
      - POSTGRES_USER=${PGIS_USER}
      - POSTGRES_PASSWORD=${PGIS_PASSWORD}
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
